# Generated by Django 4.2.4 on 2023-08-22 22:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("user", models.CharField(max_length=300)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=2000)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                ("created_by", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="CollectionDevice",
            fields=[
                (
                    "collection_uuid",
                    models.UUIDField(
                        default=uuid.UUID("3abd9932-4cde-4aa5-8ed7-f83281dc5830"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
