# Generated by Django 4.1.7 on 2023-08-03 22:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collectiondevice',
            name='collection_uuid',
            field=models.UUIDField(default=uuid.UUID('53016399-3d5d-4bd4-9dca-15502145b019'), editable=False, primary_key=True, serialize=False),
        ),
    ]
