# Generated by Django 4.2.4 on 2023-10-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("floto_api", "0002_add_collection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectiondevice",
            name="device_uuid",
            field=models.UUIDField(),
        ),
    ]
