# Generated by Django 4.2.4 on 2023-10-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floto_api', '0003_alter_collectiondevice_device_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiondevice',
            name='device_uuid',
            field=models.CharField(max_length=36),
        ),
    ]
