# Generated by Django 4.1.7 on 2023-08-04 19:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_jobdevice_device_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiondevice',
            name='collection_uuid',
            field=models.UUIDField(default=uuid.UUID('61163663-2456-416f-b351-818ad4ed9833'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobdevice',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.job'),
        ),
        migrations.CreateModel(
            name='JobTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.CharField(max_length=2000)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timings', to='api.job')),
            ],
        ),
    ]
