# Generated by Django 4.2.6 on 2024-02-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("floto_api", "0008_fleet_devicedata_fleet"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleet",
            name="is_app_fleet",
            field=models.BooleanField(default=False),
        ),
    ]
