# Generated by Django 4.2.6 on 2024-02-02 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floto_api', '0009_fleet_is_app_fleet'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
