# Generated by Django 4.2.9 on 2024-02-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floto_api', '0012_alter_peripheralconfigurationitem_peripheral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='address_1',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='address_2',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='city',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='deployment_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='latitude',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='longitude',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='state',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='zip_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
