# Generated by Django 4.2.9 on 2024-02-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floto_api', '0016_alter_serviceperipheral_service_serviceport'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='status',
            field=models.CharField(blank=True, choices=[('retired', 'retired'), ('', '--will use balena status--')], max_length=512),
        ),
    ]
