# Generated by Django 4.2.9 on 2024-03-20 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("floto_api", "0017_devicedata_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaimableResource",
            fields=[
                (
                    "resource",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="is_single_tenant",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="ServiceClaimableResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="floto_api.claimableresource",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="floto_api.service",
                    ),
                ),
            ],
        ),
    ]
