# Generated by Django 4.2.9 on 2024-03-25 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("floto_api", "0018_claimableresource_application_is_single_tenant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicetimeslot",
            name="timing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeslots",
                to="floto_api.jobtiming",
            ),
        ),
        migrations.AlterField(
            model_name="devicedata",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("", "--will use balena status--"), ("retired", "retired")],
                max_length=512,
            ),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DONE", "Done"),
                            ("ERROR", "Error"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "timing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="floto_api.jobtiming",
                    ),
                ),
            ],
        ),
    ]
