# Generated by Django 4.2.9 on 2024-04-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("floto_api", "0019_devicetimeslot_timing_alter_devicedata_status_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="deleted",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="collection",
            name="deleted",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="deleted",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="deleted",
            field=models.DateTimeField(null=True),
        ),
    ]
