# Generated by Django 4.2.11 on 2024-04-16 14:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('floto_api', '0020_application_deleted_collection_deleted_job_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='status',
            field=models.CharField(blank=True, choices=[('retired', 'retired'), ('', '--will use balena status--')], max_length=512),
        ),
        migrations.CreateModel(
            name='DownloadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(default=datetime.datetime.now)),
                ('dataset', models.CharField(max_length=1024)),
                ('downloaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
