# Generated by Django 4.2.11 on 2024-09-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("floto_api", "0022_alter_devicedata_status_dataset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="cleaned_up",
            field=models.BooleanField(default=False),
        ),
    ]
