# Generated by Django 4.2.11 on 2025-05-02 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floto_api', '0023_job_cleaned_up_alter_application_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='status',
            field=models.CharField(blank=True, choices=[('retired', 'retired'), ('', '--will use balena status--')], max_length=512),
        ),
        migrations.AlterField(
            model_name='job',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='KubernetesEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('namespace', models.CharField(blank=True, max_length=255, null=True)),
                ('event_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('involved_object_kind', models.CharField(blank=True, max_length=255, null=True)),
                ('involved_object_name', models.CharField(blank=True, max_length=255, null=True)),
                ('involved_object_namespace', models.CharField(blank=True, max_length=255, null=True)),
                ('involved_object_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('event_time', models.DateTimeField(blank=True, null=True)),
                ('first_timestamp', models.DateTimeField(blank=True, null=True)),
                ('last_timestamp', models.DateTimeField(blank=True, null=True)),
                ('source_component', models.CharField(blank=True, max_length=255, null=True)),
                ('source_host', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kubernetes_events', to='floto_api.devicedata')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kubernetes_events', to='floto_api.job')),
            ],
            options={
                'verbose_name': 'Kubernetes Event',
                'verbose_name_plural': 'Kubernetes Events',
                'ordering': ['-event_time'],
            },
        ),
    ]
