version: "3.5"

services:
  floto:
    container_name: floto_web
    image: floto-dev:latest
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${FLOTO_PORT}"]
      timeout: 10s
      retries: 3
    env_file:
      - .env
    volumes:
      - .:/project
      - ./media:/media
      - ./keys:/keys
      - static:/static
    ports:
      - "127.0.0.1:8080:${FLOTO_PORT}"
    entrypoint: ["python3", "manage.py"]
    command: ["runserver", "0.0.0.0:${FLOTO_PORT}"]
    depends_on:
      - db

  db:
    container_name: floto_db
    image: mariadb:${DB_IMG_TAG}
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d

volumes:
  static:
