version: "3.5"

services:
  floto:
    container_name: floto_web
    image: floto-dev:latest
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      timeout: 10s
      retries: 3
    env_file:
      - .env
    volumes:
      - .:/project
      - ./media:/media
      - ./config:/config
      - static:/static
    ports:
      - "8080:8080"
    entrypoint: ["python3", "manage.py"]
    command: ["runserver", "0.0.0.0:8080"]
    depends_on:
      - db
    build:
      dockerfile: Dockerfile

  db:
    container_name: floto_db
    image: mariadb:${DB_IMG_TAG}
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql

  redis: # Used for celery tasks
    image: redis:alpine

  celery:
    container_name: floto_tasks
    image: floto-dev:latest
    restart: on-failure
    entrypoint: ["celery"]
    command:
      ["-A", "floto", "worker", "-l", "INFO", "--concurrency=1", "-B"]
    env_file:
      - .env
    volumes:
      - .:/project
      - ./config:/config
    depends_on:
      - db
      - redis


volumes:
  static:
